### ISSUE TITLE
Implement Components

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-ui#116]
Umbrella issue for keeping tabs on the progress of implementing the Vue components required by the GUI and the workflow "views":

* [x] Task / Job status icons - #100
* [ ] Workflow icons - #190 
* [ ] Cylc "header" (logo and user@host selector) - #120 
* [x] Suite Control Toolbar - #114
* [x] Warning Triangle - #137
* [ ] Right-Click Menu(s)? - #138
* [ ] Tabs for different views - #98
* [ ] Tree - #145 #203
* [ ] Table - #230

**Comment by kinow** [comment]
> Right-Click Menu(s)?

Would we have an alternative for tablet/mobile in the design too? Maybe some sort of dialog popping up on click?

**Comment by hjoliver** [comment]
touch-and-hold?

**Comment by kinow** [comment]
>touch-and-hold?

Could be, not too sure if that works well. Normally touch and hold is used to select/copy/paste, etc... but could work?

**Comment by hjoliver** [comment]
On my Android phone, touch-and-hold on app icons brings up a menu, e.g. in Chrome browser for "new tab", "remove" (from desktop), "uninstall"...

**Comment by kinow** [comment]
Ah, yes, that's correct. But I think the right click / touch-and-hold in this context would happen in a browser window. On my Android, Ffox and Chrome have the same behaviour for touch-and-hold, displaying options to select/copy/paste text. (and I think a native app would effectively be running a browser window too?)

**Comment by hjoliver** [comment]
Good point!  Ok, scratch that idea. :+1:

**Comment by oliver-sanders** [comment]
> touch-and-hold?

Single tap?

**Comment by matthewrmshin** [comment]
Single tap should work here (as it can be seen as a operation to drill down for more detail.) Otherwise, you will need to have the `...` button (or vertical version of it) to show the context menu.

**Comment by oliver-sanders** [comment]
Closed in favour of a GitHub project - https://github.com/cylc/cylc-ui/projects/4

**Comment by hjoliver** [comment]
@oliver-sanders - we decided to use ZenHub instead of GitHub projects, for its full-project awareness ... do you have a good argument against that, or had just forgotten? (I'm aware that we haven't really been using ZenHub yet, but was planning to push it again next meeting).

**Comment by oliver-sanders** [comment]
> we decided to use ZenHub instead of GitHub projects

I wasn't sure we were still going for ZenHub, happy to transfer. These projects relate only to the Cylc UI so there isn't any need for cross-repo coordination.

**Comment by hjoliver** [comment]
It might be a good reason to start using ZenHub properly?  (But if it seem painful when you try it, we can reconsider...)
