### ISSUE TITLE
Close mutation editor on submission

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-ui#835]
**Describe exactly what you would like to see in an upcoming release**

[edit] updated, see comments bellow

- [x] Remove the old task icon status thinggy (was never intended to be released). (#1108)
- [x] Make the dialogue box close on successful submission of a mutation. (#1160)
- [x] Keep the dialogue box open for an unsuccessful submission and raise an Alert (if not already done). (#1160)
- [ ] Add a close "x" button to the top right of the mutation editor form, as well as the mutation menu

[/edit]

The following dialog is fully functional but some users may find having to close with the cancel button confusing.

In my opinion these dialogs should have a cross which copies the functionality of the cancel button at either the top right or top left corner.

![image](https://user-images.githubusercontent.com/26465611/140308188-cafbe827-797d-4771-aa3a-6d411101c940.png)

**Pull requests welcome!**

**Comment by hjoliver** [comment]
I agree. "Cancel" could easily be confused with trying to cancel the mutation you've just submitted.

**Comment by oliver-sanders** [comment]
The box should close once the mutation has been submitted.

At the moment it doesn't for debug purposes, I think when you submit a mutation you still get a task icon showing the status of the mutation (i.e. waiting, submitted or submit-failed).

Propose the following:

* Remove the old task icon status thinggy (was never intended to be released).
* Make the dialogue box close on successful submission of a mutation.
* Keep the dialogue box open for an unsuccessful submission and raise an Alert (if not already done).

**Comment by oliver-sanders** [comment]
Two likes no screams, removing the question label.

**Comment by MetRonnie** [comment]
The mutation menu could also do with an "x" close button, because for small viewports there is likely to barely be any room to tap outside the menu in order to close it. I have added this (and the close button for the mutation editor form) as a bullet point

**Comment by oliver-sanders** [comment]
(alternatively ensure the cancel button is always visible e.g. via a sticky footer)

**Comment by oliver-sanders** [comment]
Suggest putting the submit and cancel buttons in a stick footer at the bottom of the form so they are always visible as this will also be useful for the submit button (we don't always need to scroll to the bottom).
